worker_processes  2;

include modules.d/*.conf;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    types_hash_max_size 4096;
    types_hash_bucket_size 64;
    server_names_hash_bucket_size 96;
    sendfile        on;
    keepalive_timeout  65;
    proxy_buffer_size 16k;
    proxy_buffers 256 16k;
    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/proxy/*.conf;

    server {
        listen 80 default_server;

        rewrite ^(.*) https://$host$1 permanent;
    }
}
